//! The autorouter operations of the U8 replay vectors (`testdata/autoroute/*.txt`, generated by
//! `testdata/autoroute/AutorouteGen.java`). Included by `board_replay.rs`.

use std::cell::RefCell;
use std::fmt::Write as _;

use fr_engine::autoroute::control::AutorouteControl;
use fr_engine::autoroute::engine::{AutorouteEngine, Expandable};
use fr_engine::autoroute::inserter::FoundConnectionInserter;
use fr_engine::autoroute::locator::FoundConnectionLocator;
use fr_engine::autoroute::maze::MazeSearchEngine;
use fr_engine::autoroute::router::{route_connection, ConnectionRouterParams};
use fr_engine::board::*;
use fr_engine::ids::ItemId;
use fr_engine::rules::{ViaInfo, ViaRule};
use fr_settings::RouterSettings;

use super::{block, d, tile, Tok};

thread_local! {
    static SETTINGS: RefCell<Option<RouterSettings>> = const { RefCell::new(None) };
    /// The output mode: "hash", "expand" (all blocks expanded) or "steps" (the maze steps without
    /// header, the rooms expanded).
    static MODE: RefCell<String> = const { RefCell::new(String::new()) };
    /// Retain the autoroute database (Java `retainAutorouteDatabase`).
    static RETAIN: RefCell<bool> = const { RefCell::new(false) };
}

fn key(board: &RoutingBoard, t: &mut Tok) -> ItemKey {
    let id = t.i32();
    board.get_item(ItemId(id)).unwrap_or_else(|| panic!("item {id} not found"))
}

fn settings() -> RouterSettings {
    SETTINGS.with(|s| s.borrow().clone().expect("ARSETTINGS missing"))
}

fn ids(set: &ItemSet) -> String {
    let v: Vec<String> = set.ids().map(|i| i.0.to_string()).collect();
    format!("[{}]", v.join(","))
}

fn state_name(s: AutorouteAttemptState) -> &'static str {
    match s {
        AutorouteAttemptState::Unknown => "UNKNOWN",
        AutorouteAttemptState::Skipped => "SKIPPED",
        AutorouteAttemptState::NoUnconnectedNets => "NO_UNCONNECTED_NETS",
        AutorouteAttemptState::ConnectedToPlane => "CONNECTED_TO_PLANE",
        AutorouteAttemptState::AlreadyConnected => "ALREADY_CONNECTED",
        AutorouteAttemptState::NoConnections => "NO_CONNECTIONS",
        AutorouteAttemptState::Routed => "ROUTED",
        AutorouteAttemptState::Failed => "FAILED",
        AutorouteAttemptState::InsertError => "INSERT_ERROR",
    }
}

fn kind(e: Expandable) -> &'static str {
    match e {
        Expandable::Door(_) => "D",
        Expandable::Target(_) => "T",
        Expandable::Drill(_) => "X",
        Expandable::Page(_) => "P",
    }
}

/// `AutorouteGen.control(netNo, pass)`.
fn control(board: &RoutingBoard, s: &RouterSettings, net_no: i32, pass: i32) -> AutorouteControl {
    let plane = board.rules.nets.get(net_no).map(|n| n.contains_plane()).unwrap_or(false);
    let via_costs = if plane { s.get_plane_via_costs() } else { s.get_via_costs() };
    let mut ctrl = AutorouteControl::new(board, net_no, s, via_costs, s.get_trace_costs());
    ctrl.ripup_allowed = true;
    ctrl.ripup_costs = s.get_start_ripup_costs() * pass;
    ctrl.remove_unconnected_vias = true;
    ctrl
}

fn rooms(eng: &AutorouteEngine, expand: bool) -> Vec<String> {
    let mut lines = Vec::new();
    for &r in eng.complete_room_list() {
        let room = eng.room(r);
        lines.push(format!("{} {} {} d {} t {}", eng.room_java_id(r), room.layer, tile(room.shape()), room.doors.len(), room.target_doors().len()));
    }
    block(format!("ROOMS {}", lines.len()), lines, expand)
}

fn queue_state(maze: &MazeSearchEngine<'_>) -> String {
    match maze.queue_first() {
        None => "0".into(),
        Some(e) => format!(
            "{} {} {} {} {} {}",
            maze.queue_len(),
            d(e.sorting_value),
            d(e.expansion_value),
            kind(e.door),
            maze.eng.expandable_java_id(e.door),
            e.section_no_of_door
        ),
    }
}

/// Start and destination set of `AutorouteConnectionRouter.route`; `None` if connected to a plane.
fn sets(board: &RoutingBoard, item: ItemKey, net_no: i32) -> Option<(ItemSet, ItemSet)> {
    let plane = board.rules.nets.get(net_no).map(|n| n.contains_plane()).unwrap_or(false);
    let unconnected = board.unconnected_set(item, net_no);
    let connected = board.connected_set(item, net_no, false);
    if plane {
        if connected.iter().any(|k| board.item(k).is_conduction_area()) {
            return None;
        }
        Some((connected, unconnected))
    } else {
        Some((unconnected, connected))
    }
}

/// Executes an autoroute operation. `None` if the operation is unknown.
pub fn execute(board: &mut RoutingBoard, op: &str, t: &mut Tok) -> Option<Vec<String>> {
    let mut out: Vec<String> = Vec::new();
    match op {
        "ARMODE" => {
            let mode = t.next().to_string();
            MODE.with(|s| *s.borrow_mut() = mode);
            let retain = t.pos < t.t.len() && t.bool();
            RETAIN.with(|s| *s.borrow_mut() = retain);
        }
        "ARFANOUT" => {
            let pin = key(board, t);
            let ripup_costs = t.i32();
            let s = settings();
            let result = board.fanout(pin, &s, ripup_costs, None, None);
            out.push(state_name(result.state).into());
        }
        "ARVIAINFO" => {
            let name = t.str();
            let padstack = t.i32();
            let cl = t.i32();
            let attach = t.bool();
            board.rules_mut().via_infos.add(ViaInfo::new(name, padstack, cl, attach)).expect("via info name not unique");
        }
        "ARVIARULE" => {
            let name = t.str();
            let n = t.i32();
            let mut rule = ViaRule::new(name);
            for _ in 0..n {
                let via_name = t.str();
                let id = board.rules.via_infos.get_by_name(&via_name).expect("via info");
                rule.append_via(id);
            }
            board.rules_mut().via_rules.add(rule);
        }
        "ARNETCLASS" => {
            let name = t.str();
            let cl = t.i32();
            let via_rule_name = t.str_opt();
            let n = t.i32();
            let rules = board.rules_mut();
            let via_rule = via_rule_name.map(|v| rules.get_via_rule(&v).expect("via rule"));
            let id = rules.net_classes.get_by_name(&name).expect("net class");
            let nc = &mut rules.net_classes[id];
            nc.set_trace_clearance_class(cl);
            nc.set_via_rule(via_rule);
            for l in 0..n {
                let hw = t.i32();
                let active = t.bool();
                nc.set_trace_half_width_on_layer(l, hw);
                nc.set_active_routing_layer(l, active);
            }
        }
        "ARSETTINGS" => {
            let n = t.i32() as usize;
            let mut s = RouterSettings::new();
            s.set_layer_count(n);
            for i in 0..n {
                let active = t.bool();
                let h = t.f64();
                let v = t.f64();
                let bend = t.f64();
                s.set_layer_active(i, active);
                s.set_preferred_direction_is_horizontal(i, true);
                s.set_preferred_direction_trace_costs(i, h);
                s.set_against_preferred_direction_trace_costs(i, v);
                s.layers.as_mut().unwrap()[i].bend_cost = Some(bend);
                assert_eq!(s.get_horizontal_trace_costs(i), h);
                assert_eq!(s.get_vertical_trace_costs(i), v);
            }
            s.vias_allowed = Some(t.bool());
            s.automatic_neckdown = Some(t.bool());
            s.scoring.via_costs = Some(t.i32());
            s.scoring.plane_via_costs = Some(t.i32());
            s.scoring.start_ripup_costs = Some(t.i32());
            s.trace_pull_tight_accuracy = Some(t.i32());
            s.fanout.min_escape_length_mm = Some(t.f64());
            s.fanout.max_escape_length_mm = Some(t.f64());
            s.neck_width_um = Some(t.f64());
            s.fanout.fallback_to_board_vias = Some(true);
            SETTINGS.with(|x| *x.borrow_mut() = Some(s));
        }
        "ARCONN" => {
            let item = key(board, t);
            let net_no = t.i32();
            let pass = t.i32();
            let s = settings();
            let params = ConnectionRouterParams {
                trace_costs: s.get_trace_costs(),
                start_ripup_costs: s.get_start_ripup_costs(),
                remove_unconnected_vias: true,
                retain_autoroute_database: RETAIN.with(|x| *x.borrow()),
                trace_pull_tight_accuracy: s.trace_pull_tight_accuracy.unwrap(),
                connect_to_planes: false,
            };
            let mut ripped = ItemSet::new();
            let outcome = route_connection(board, &s, &params, item, net_no, &mut ripped, None, pass, None);
            out.push(format!("{} {}", state_name(outcome.result.state), ids(&ripped)));
        }
        "ARSEARCH" | "ARDETAIL" => {
            let insert = op == "ARDETAIL";
            let item = key(board, t);
            if std::env::var("FR_AUTOROUTE_INFOS").is_ok() {
                let pending: Vec<ItemKey> = board.autoroute_maintenance.as_ref().map(|m| m.cleared_autoroute_info.clone()).unwrap_or_default();
                let mut ids: Vec<i32> = Vec::new();
                if let Some(eng) = board.autoroute_engine.0.as_ref() {
                    for k in board.get_items() {
                        if eng.has_item_info(k) && !pending.contains(&k) {
                            ids.push(board.item(k).id().0);
                        }
                    }
                }
                ids.sort();
                let mut s = String::from("INFOS");
                for i in ids {
                    write!(s, " {i}").unwrap();
                }
                out.push(s);
            }
            let net_no = t.i32();
            let pass = t.i32();
            let s = settings();
            let mode = MODE.with(|x| x.borrow().clone());
            let expand = mode != "hash";
            let ctrl = control(board, &s, net_no, pass);
            let Some((start, dest)) = sets(board, item, net_no) else {
                out.push("PLANE".into());
                return Some(out);
            };
            let retain = RETAIN.with(|x| *x.borrow());
            board.init_autoroute(net_no, ctrl.trace_clearance_class, None, None, retain);
            let mut eng = board.autoroute_engine.take().unwrap();
            let search_result;
            {
                let Some(mut maze) = MazeSearchEngine::get_instance(&start, &dest, &mut eng, board, &ctrl) else {
                    out.push("NOINSTANCE".into());
                    out.extend(rooms(&eng, expand));
                    board.autoroute_engine.0 = Some(eng);
                    return Some(out);
                };
                let trace_added = std::env::var("FR_AUTOROUTE_ADDED").is_ok();
                let mut step_lines = vec![queue_state(&maze)];
                loop {
                    if trace_added {
                        maze.trace_added = Some(Vec::new());
                    }
                    let more = maze.occupy_next_element();
                    step_lines.push(queue_state(&maze));
                    if let Some(added) = maze.trace_added.take() {
                        // (Java lists the added elements still in the queue in queue order)
                        let mut still: Vec<usize> = maze.queue.iter().copied().filter(|i| added.contains(i)).collect();
                        still.dedup();
                        for i in still {
                            let e = &maze.elements[i];
                            let nr = e.next_room.map(|r| maze.eng.room_java_id(r).to_string()).unwrap_or_else(|| "-".into());
                            step_lines.push(format!(
                                "+ {} {} {} {} {} {}",
                                d(e.sorting_value),
                                d(e.expansion_value),
                                kind(e.door),
                                maze.eng.expandable_java_id(e.door),
                                e.section_no_of_door,
                                nr
                            ));
                        }
                    }
                    if !more {
                        break;
                    }
                }
                if mode == "steps" {
                    out.extend(step_lines);
                } else {
                    out.extend(block(format!("STEPS {}", step_lines.len()), step_lines, expand));
                }
                search_result = maze.find_connection();
            }
            match &search_result {
                None => out.push("RESULT -".into()),
                Some(r) => out.push(format!("RESULT {} {} {}", kind(r.destination_door), r.section_no_of_door, eng.expandable_java_id(r.destination_door))),
            }
            out.extend(rooms(&eng, expand));
            let mut ripped = ItemSet::new();
            let mut locator = None;
            if let Some(r) = &search_result {
                let angle = board.rules.get_trace_angle_restriction();
                match FoundConnectionLocator::get_instance(r, &ctrl, &mut eng, board, angle, &mut ripped, None) {
                    Err(_) => out.push("LOCATOR -".into()),
                    Ok(loc) => {
                        let item_id = |k: Option<ItemKey>| k.map(|k| board.item(k).id().0.to_string()).unwrap_or_else(|| "-".into());
                        let mut s = format!(
                            "LOCATOR {} {} {} {} {}",
                            item_id(loc.start_item),
                            loc.start_layer,
                            item_id(loc.target_item),
                            loc.target_layer,
                            loc.connection_items.len()
                        );
                        for ri in &loc.connection_items {
                            write!(s, " | {} {}", ri.layer, ri.corners.len()).unwrap();
                            for c in &ri.corners {
                                write!(s, " {} {}", c.x, c.y).unwrap();
                            }
                        }
                        out.push(s);
                        locator = Some(loc);
                    }
                }
            }
            out.push(format!("RIPPED {}", ids(&ripped)));
            if retain {
                eng.reset_all_doors(board);
            } else {
                eng.clear(board);
            }
            board.autoroute_engine.0 = Some(eng);
            if insert {
                // the rest of AutorouteEngine.autorouteConnection
                let mut state = AutorouteAttemptState::Failed;
                if let Some(loc) = &locator {
                    if ctrl.layer_active[loc.start_layer as usize] && ctrl.layer_active[loc.target_layer as usize] {
                        let opt = if ctrl.remove_unconnected_vias { StopConnectionOption::None } else { StopConnectionOption::FanoutVia };
                        let mut ripped_connections = ItemSet::new();
                        let mut changed_nets = std::collections::BTreeSet::new();
                        for r in ripped.iter() {
                            ripped_connections.extend_from(&board.get_connection_items(r, opt));
                            changed_nets.extend(board.item(r).net_numbers().iter().copied());
                        }
                        board.remove_items(ripped_connections.iter().collect::<Vec<_>>());
                        for n in changed_nets {
                            board.remove_trace_tails(n, opt);
                        }
                        if FoundConnectionInserter::get_instance(loc, board, &ctrl).is_some() {
                            state = AutorouteAttemptState::Routed;
                        }
                    }
                }
                if state == AutorouteAttemptState::Routed {
                    board.opt_changed_area(&[], None, s.trace_pull_tight_accuracy.unwrap(), Some(&ctrl.trace_costs), None, 1000);
                }
                out.push(format!("STATE {}", state_name(state)));
            }
        }
        _ => return None,
    }
    Some(out)
}
