//! The routing board operations of the U7 replay vectors (`testdata/routing/*.txt`, generated by
//! `testdata/routing/RoutingGen.java`). Included by `board_replay.rs`.

use fr_engine::board::actions::{drill_item_mover, forced_via_inserter, CheckDrillResult};
use fr_engine::board::optimize::{via_optimizer, TraceShover};
use fr_engine::board::*;
use fr_engine::ids::ItemId;
use fr_engine::rules::ViaInfo;
use fr_geom::*;
use fr_settings::ExpansionCostFactor;

use super::{b, d, pt, Tok};

use fr_engine::board::optimize::TraceTightener;
use std::cell::RefCell;

thread_local! {
    /// The tightener of the stepped optChangedArea operations (TTNEW ... ENDMARK).
    static TIGHTENER: RefCell<Option<TraceTightener>> = const { RefCell::new(None) };
}

fn key(board: &RoutingBoard, t: &mut Tok) -> ItemKey {
    let id = t.i32();
    // removed items may still be referenced by Java (tombstones): search the arena too
    board.get_item(ItemId(id)).unwrap_or_else(|| panic!("item {id} not found"))
}

fn costs(t: &mut Tok) -> Option<Vec<ExpansionCostFactor>> {
    if t.peek() == "N" {
        t.next();
        return None;
    }
    assert_eq!(t.next(), "C");
    let n = t.i32();
    Some((0..n).map(|_| ExpansionCostFactor { horizontal: t.f64(), vertical: t.f64() }).collect())
}

fn via_info(t: &mut Tok) -> ViaInfo {
    let ps = t.i32();
    let cl = t.i32();
    let attach = t.bool();
    ViaInfo::new("replay", ps, cl, attach)
}

/// Executes a routing operation. `None` if the operation is unknown.
pub fn execute(board: &mut RoutingBoard, op: &str, t: &mut Tok) -> Option<Vec<String>> {
    let mut out: Vec<String> = Vec::new();
    match op {
        "SNAP" => board.generate_snapshot(),
        "UNDO" => out.push(b(board.undo(None)).into()),
        "POPSNAP" => out.push(b(board.pop_snapshot()).into()),
        "MARKALL" => board.mark_all_changed_area(),
        "STARTMARK" => board.start_marking_changed_area(),
        "JOINAREA" => {
            let x = t.f64();
            let y = t.f64();
            let layer = t.i32();
            board.join_changed_area(&FloatPoint::new(x, y), layer);
        }
        "OPT" => {
            let acc = t.i32();
            let nets = t.nets();
            let clip = t.opt_tile().map(|s| match s {
                TileShape::IntOctagon(o) => o,
                other => panic!("OPT: octagon expected, got {other:?}"),
            });
            let c = costs(t);
            board.opt_changed_area(&nets, clip, acc, c.as_deref(), None, 0);
        }
        "PULLTIGHT" => {
            let k = key(board, t);
            let own = t.bool();
            let acc = t.i32();
            out.push(b(board.pull_tight_trace(k, own, acc, None)).into());
        }
        "SMOOTHFORK" => {
            let k = key(board, t);
            let own = t.bool();
            let acc = t.i32();
            out.push(b(board.smoothen_end_corners_fork(k, own, acc, None)).into());
        }
        "OPTVIA" => {
            let k = key(board, t);
            let acc = t.i32();
            let c = costs(t);
            out.push(b(via_optimizer::opt_via_location(board, k, c.as_deref(), acc, 10)).into());
        }
        "CHECKSEG" => {
            let from = t.point();
            let to = t.point();
            let layer = t.i32();
            let nets = t.nets();
            let hw = t.i32();
            let cl = t.i32();
            let only = t.bool();
            out.push(d(board.check_trace_segment(&from, &to, layer, &nets, hw, cl, only)));
        }
        "SHOVESEG" => {
            let from = t.point();
            let to = t.point();
            let left = t.bool();
            let layer = t.i32();
            let nets = t.nets();
            let hw = t.i32();
            let cl = t.i32();
            let max_rec = t.i32();
            let max_via = t.i32();
            let pl = Polyline::from_two_points(&from, &to);
            let seg = LineSegment::from_polyline(&pl, 1).unwrap();
            out.push(d(TraceShover::check_line_segment(board, &seg, left, layer, &nets, hw, cl, max_rec, max_via)));
        }
        "FPOLYCHECK" => {
            let n = t.i32();
            let pts: Vec<Point> = (0..n).map(|_| t.point()).collect();
            let hw = t.i32();
            let layer = t.i32();
            let nets = t.nets();
            let cl = t.i32();
            let max_rec = t.i32();
            let max_via = t.i32();
            let max_spring = t.i32();
            let pl = Polyline::from_points(&pts);
            out.push(b(board.check_forced_trace_polyline(&pl, hw, layer, &nets, cl, max_rec, max_via, max_spring)).into());
        }
        "QSF" => {
            let f = board.shove_failing_obstacle().map(|k| board.item(k).id().0.to_string()).unwrap_or_else(|| "-".into());
            out.push(format!("{} {}", f, board.shove_failing_layer()));
        }
        "FTRACE" => {
            let from = t.point();
            let to = t.point();
            let hw = t.i32();
            let layer = t.i32();
            let nets = t.nets();
            let cl = t.i32();
            let max_rec = t.i32();
            let max_via = t.i32();
            let max_spring = t.i32();
            let tidy = t.i32();
            let acc = t.i32();
            let with_check = t.bool();
            let r = board.insert_forced_trace_segment(&from, &to, hw, layer, &nets, cl, max_rec, max_via, max_spring, tidy, acc, with_check, None);
            out.push(match r {
                ForcedTraceEnd::Failed => "N".into(),
                ForcedTraceEnd::From(_) => "F".into(),
                ForcedTraceEnd::To(_) => "T".into(),
                ForcedTraceEnd::Other(p) => format!("O {}", pt(&p)),
            });
        }
        "FVIACHECK" => {
            let vi = via_info(t);
            let loc = t.point();
            let nets = t.nets();
            let max_rec = t.i32();
            let max_via = t.i32();
            let pen = t.nets();
            let trace_cl = t.i32();
            out.push(b(forced_via_inserter::check(board, &vi, &loc, &nets, max_rec, max_via, Some(&pen), trace_cl)).into());
        }
        "FVIALAYER" => {
            let radius = t.f64();
            let cl = t.i32();
            let attach = t.bool();
            let room = t.tile();
            let loc = t.point();
            let layer = t.i32();
            let nets = t.nets();
            let max_rec = t.i32();
            let max_via = t.i32();
            let hw = t.i32();
            let trace_cl = t.i32();
            let r = forced_via_inserter::check_layer(board, radius, cl, attach, &room, &loc, layer, &nets, max_rec, max_via, hw, trace_cl);
            out.push(
                match r {
                    CheckDrillResult::Drillable => "0",
                    CheckDrillResult::DrillableWithAttachSmd => "1",
                    CheckDrillResult::NotDrillable => "2",
                }
                .into(),
            );
        }
        "FVIA" => {
            let vi = via_info(t);
            let loc = t.point();
            let nets = t.nets();
            let trace_cl = t.i32();
            let pen = t.nets();
            let max_rec = t.i32();
            let max_via = t.i32();
            out.push(b(forced_via_inserter::insert(board, &vi, &loc, &nets, trace_cl, &pen, max_rec, max_via)).into());
        }
        "DRILLCHECK" | "DRILLMOVE" => {
            let k = key(board, t);
            let v = t.vector();
            let max_rec = t.i32();
            let max_via = t.i32();
            let r = if op == "DRILLCHECK" {
                drill_item_mover::check(board, k, &v, max_rec, max_via, None, None)
            } else {
                drill_item_mover::insert(board, k, &v, max_rec, max_via)
            };
            out.push(b(r).into());
        }
        "CONNTRACE" => {
            let x = t.i32();
            let y = t.i32();
            let k = key(board, t);
            let hw = t.i32();
            let cl = t.i32();
            out.push(b(board.connect_to_trace(&IntPoint::new(x, y), k, hw, cl)).into());
        }
        "REDUCENETS" => out.push(b(board.reduce_nets_of_route_items()).into()),
        "RMTAILS" => {
            let net = t.i32();
            let opt = match t.i32() {
                0 => StopConnectionOption::None,
                1 => StopConnectionOption::FanoutVia,
                _ => StopConnectionOption::Via,
            };
            out.push(b(board.remove_trace_tails(net, opt)).into());
        }
        "PLANEOBST" => {
            let v = t.bool();
            board.change_plane_as_obstacle(v);
        }
        "TTNEW" => {
            let acc = t.i32();
            let nets = t.nets();
            let clip = t.opt_tile().map(|s| match s {
                TileShape::IntOctagon(o) => o,
                other => panic!("TTNEW: octagon expected, got {other:?}"),
            });
            let algo = TraceTightener::get_instance(board, &nets, clip, acc, None, 0, None, 0);
            TIGHTENER.with(|x| *x.borrow_mut() = Some(algo));
        }
        "TTEMPTY" => {
            let layer = t.i32();
            board.changed_area.as_mut().unwrap().set_empty(layer);
        }
        "TTPULL" | "TTSMOOTH" => {
            let id = t.i32();
            // removed traces: both calls return false without side effects
            let r = match board.get_item(ItemId(id)) {
                None => false,
                Some(k) => TIGHTENER.with(|x| {
                    let mut g = x.borrow_mut();
                    let algo = g.as_mut().unwrap();
                    if op == "TTPULL" {
                        algo.pull_tight_trace(board, k)
                    } else {
                        algo.smoothen_end_corners_at_trace(board, k)
                    }
                }),
            };
            out.push(b(r).into());
        }
        "TTKEEP" => {
            let r = TIGHTENER.with(|x| x.borrow_mut().as_mut().unwrap().split_traces_at_keep_point(board));
            out.push(b(r).into());
        }
        "ENDMARK" => board.changed_area = None,
        "DEEPCOPY" => *board = board.deep_copy(),
        _ => return None,
    }
    Some(out)
}
