[package]
name = "fastroute"
description = "Command-line PCB autorouter (Rust port of Freerouting)"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
fr-dsn = { path = "../fr-dsn" }
fr-settings = { path = "../fr-settings" }
fr-io = { path = "../fr-io" }
fr-engine = { path = "../fr-engine" }
log = "0.4"

[dev-dependencies]
fr-geom = { path = "../fr-geom" }
